server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-connections: 10000
    min-spare-threads: 30
spring:
  application:
    name: boot-admin-scaffold
  profiles:
    active: dev
  #关闭thymeleaf的缓存，不然在开发过程中修改页面不会立刻生效需要重启，生产可配置为true
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  # xml 扫描路径 Mapper中有自定义方法需要
  mapper-locations: classpath:mapper/*/*.xml
  # 给包中的类注册别名 注册后在 Mapper 对应的 XML 文件中可以直接使用类名
  typeAliasesPackage: com.anthonyzero.scaffold.system.entity
  configuration:
    jdbc-type-for-null: null
  global-config:
    #关闭 mybatis-plus的 banner
    banner: false