spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
          url: jdbc:mysql://47.107.119.239:3306/scaffold?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
          username: root
          password: pingjin100
          initial-size: 10
          max-active: 100
          min-idle: 10
          max-wait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          time-between-eviction-runs-millis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          stat-view-servlet:
            enabled: true
            url-pattern: /druid/*
            login-username: pingjin
            login-password: pingjin
          filter:
            stat:
              log-slow-sql: true
              slow-sql-millis: 1000
              merge-sql: true
            wall:
              config:
                multi-statement-allow: true
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379
      password:
      jedis:
        pool:
          max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
          min-idle: 5      # 连接池中的最小空闲连接
          max-idle: 10     # 连接池中的最大空闲连接
          max-wait: 1000   # 连接池最大阻塞等待时间
      timeout: 6000